name: Use Tecture Publisher

on:
  pull_request:
    types: [closed]

jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Tecture Component Library Publisher
        uses: tecture-io/component-library-publisher-action@v0.0.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          database_key: 'not a secret'
