name: Publish to Tecture (Production)

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Tecture Component Library Publisher
        uses: tecture-io/component-library-publisher-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          server_url: ${{ secrets.SERVER_URL_PROD }}
          auth_url: ${{ secrets.AUTH_URL }}
          client_id: ${{ secrets.CLIENT_ID }}
          client_secret: ${{ secrets.CLIENT_SECRET }}
          audience: ${{ secrets.AUDIENCE }}
